name: Deploy Application

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            cd /home/ubuntu/janikoke_lara
            git pull origin main
            ./vendor/bin/sail artisan migrate --force
            ./vendor/bin/sail artisan optimize
            ./vendor/bin/sail artisan challenges:update-center-points
            ./vendor/bin/sail artisan areas:update-centroids
            docker compose -f docker-compose.yml build google-auth-service
            docker compose -f docker-compose.yml up -d google-auth-service
            npm run build
